apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: argo 
    namespace: argocd
spec:
    project: default

    source:
        repoURL: YOUR_GITHUB_HERE
        targetRevision: HEAD
        path: k8s

    destination:
        server: https://kubernetes.default.svc
        namespace: app

    syncPolicy:
        syncOptions:
        - PruneLast=true
          ApplyOutOfSyncOnly=true
          PrunePropagationPolicy=foreground
          CreateNamespace=true
        automated:
            selfHeal: true
            prune: true
